import type {
  UserProfile,
  UserThread,
  UserComment,
  Bookmark,
  Notification,
  DashboardStats,
} from '@/types/user-dashboard';

export const mockUserProfile: UserProfile = {
  id: '1',
  displayName: 'Somchai Developer',
  email: 'somchai@example.com',
  avatar: undefined,
  bio: 'Full-stack developer ที่ชอบแชร์ความรู้และเรียนรู้สิ่งใหม่ๆ อยู่เสมอ',
  location: 'Bangkok, Thailand',
  website: 'https://somchai.dev',
  socialLinks: {
    twitter: 'somchai_dev',
    github: 'somchai',
    linkedin: 'somchai-dev',
  },
  stats: {
    threads: 45,
    comments: 234,
    likes: 567,
    followers: 89,
    following: 123,
  },
  joinedAt: '2025-03-15T10:00:00Z',
};

export const mockUserThreads: UserThread[] = [
  {
    id: '1',
    title: 'วิธีเริ่มต้นเรียน React สำหรับมือใหม่',
    slug: 'how-to-start-react',
    excerpt: 'แชร์ประสบการณ์และ resources ดีๆ สำหรับคนที่อยากเริ่มเรียน React',
    categoryId: '1',
    categoryName: 'การเขียนโปรแกรม',
    status: 'active',
    isPinned: false,
    viewCount: 234,
    voteCount: 45,
    commentCount: 12,
    createdAt: '2025-09-28T14:30:00Z',
    updatedAt: '2025-10-01T10:20:00Z',
  },
  {
    id: '2',
    title: 'เปรียบเทียบ Next.js 14 vs 13 มีอะไรเปลี่ยนแปลงบ้าง',
    slug: 'nextjs-14-vs-13',
    excerpt: 'สรุปฟีเจอร์ใหม่และการเปลี่ยนแปลงสำคัญใน Next.js 14',
    categoryId: '1',
    categoryName: 'การเขียนโปรแกรม',
    status: 'active',
    isPinned: true,
    viewCount: 456,
    voteCount: 78,
    commentCount: 23,
    createdAt: '2025-09-25T09:15:00Z',
    updatedAt: '2025-09-30T16:45:00Z',
  },
  {
    id: '3',
    title: 'สอบถามเรื่อง TypeScript Generic',
    slug: 'typescript-generic-question',
    categoryId: '1',
    categoryName: 'การเขียนโปรแกรม',
    status: 'active',
    isPinned: false,
    viewCount: 123,
    voteCount: 15,
    commentCount: 8,
    createdAt: '2025-09-20T11:00:00Z',
    updatedAt: '2025-09-22T14:30:00Z',
  },
];

export const mockUserComments: UserComment[] = [
  {
    id: '1',
    content: 'ขอบคุณสำหรับบทความดีๆ ครับ ได้ความรู้เยอะเลย',
    threadId: '10',
    threadTitle: '10 เทคนิคการเขียน Clean Code',
    voteCount: 12,
    createdAt: '2025-10-01T15:30:00Z',
    updatedAt: '2025-10-01T15:30:00Z',
  },
  {
    id: '2',
    content: 'ผมลองใช้วิธีนี้แล้วได้ผลดีมากครับ แนะนำเลย',
    threadId: '11',
    threadTitle: 'วิธีเพิ่มประสิทธิภาพ React App',
    voteCount: 8,
    createdAt: '2025-09-30T10:20:00Z',
    updatedAt: '2025-09-30T10:20:00Z',
  },
  {
    id: '3',
    content: 'มีตัวอย่าง code ให้ดูเพิ่มเติมได้ไหมครับ',
    threadId: '12',
    threadTitle: 'การใช้ Redux Toolkit',
    parentCommentId: '50',
    voteCount: 3,
    createdAt: '2025-09-29T14:15:00Z',
    updatedAt: '2025-09-29T14:15:00Z',
  },
];

export const mockBookmarks: Bookmark[] = [
  {
    id: '1',
    threadId: '20',
    threadTitle: 'สรุปหลักการ SOLID Principles แบบเข้าใจง่าย',
    threadExcerpt: 'อธิบายหลัก SOLID ทั้ง 5 ข้อพร้อมตัวอย่าง',
    categoryName: 'การเขียนโปรแกรม',
    authorName: 'Jane Smith',
    bookmarkedAt: '2025-10-01T09:00:00Z',
  },
  {
    id: '2',
    threadId: '21',
    threadTitle: 'Resources เรียน Web Development แบบ Self-Study',
    threadExcerpt: 'รวม resources ดีๆ สำหรับคนเรียนด้วยตัวเอง',
    categoryName: 'การเขียนโปรแกรม',
    authorName: 'John Doe',
    bookmarkedAt: '2025-09-28T16:45:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'reply',
    title: 'มีคนตอบกระทู้ของคุณ',
    message: 'John Doe ตอบกระทู้ "วิธีเริ่มต้นเรียน React สำหรับมือใหม่"',
    actionUrl: '/threads/how-to-start-react',
    isRead: false,
    createdAt: '2025-10-02T08:30:00Z',
  },
  {
    id: '2',
    type: 'vote',
    title: 'กระทู้ของคุณได้รับโหวต',
    message: 'กระทู้ "เปรียบเทียบ Next.js 14 vs 13" ได้รับโหวต 5 ครั้ง',
    actionUrl: '/threads/nextjs-14-vs-13',
    isRead: false,
    createdAt: '2025-10-01T18:20:00Z',
  },
  {
    id: '3',
    type: 'comment',
    title: 'มีความคิดเห็นใหม่',
    message: 'Jane Smith แสดงความคิดเห็นในกระทู้ของคุณ',
    actionUrl: '/threads/how-to-start-react',
    isRead: true,
    createdAt: '2025-10-01T14:15:00Z',
  },
  {
    id: '4',
    type: 'follow',
    title: 'มีผู้ติดตามใหม่',
    message: 'Alex Johnson เริ่มติดตามคุณแล้ว',
    actionUrl: '/users/alex-johnson',
    isRead: true,
    createdAt: '2025-09-30T11:00:00Z',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalThreads: 45,
  totalComments: 234,
  totalLikes: 567,
  totalViews: 12456,
  recentActivity: [
    { date: '2025-09-26', threads: 2, comments: 8 },
    { date: '2025-09-27', threads: 1, comments: 12 },
    { date: '2025-09-28', threads: 3, comments: 15 },
    { date: '2025-09-29', threads: 0, comments: 9 },
    { date: '2025-09-30', threads: 2, comments: 11 },
    { date: '2025-10-01', threads: 1, comments: 14 },
    { date: '2025-10-02', threads: 0, comments: 6 },
  ],
};
